import "./globals.css";
import Header from "./_components/header";
import SideBar from "./_components/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-[--body-bg] w-full flex-col h-fit md:h-screen overflow-hidden">
        <div className="w-full flex">
          <Header />
        </div>
        <div className="flex w-full gap-4">
          <SideBar />
          <div className="h-screen relative overflow-y-scroll w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
